### ISSUE TITLE
Village Train Station Using Outdated create:andesite_bricks Block in Jigsaw Crash

### ISSUE THREAD

**Issue by liopyu** [sudolev/DynamicVillageMod#11]
This causes a crash when the train station is loaded in with this crash message

The correct block should now be create:cut_andesite_bricks
minecraft version 1.19.2
mod version- latest
Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown block type 'create:andesite_bricks' at position 0:

![image](https://github.com/sudolev/DynamicVillageMod/assets/130418550/52e713c3-07ab-40db-9d60-da9412ef353f)

![image](https://github.com/sudolev/DynamicVillageMod/assets/130418550/f0be4cff-23de-4bf7-b26d-bb387e00e82a)

**Comment by sudolev** [comment]
Thanks for the issue, really appreciate it. Gonna work on fixing this.

**Comment by liopyu** [comment]
thank you!!

**Comment by sudolev** [comment]
Should be fixed in newest version :)
