### ISSUE TITLE
Vietnamese pls

### ISSUE THREAD

**Issue by kienerxyzzy** [sudolev/DynamicVillageMod#18]
{
  "entity.minecraft.villager.dynamicvillage.mechanical_engineer": "Kỹ sư cơ khí",
  "entity.minecraft.villager.dynamicvillage.hydraulic_engineer": "Kỹ sư thủy lực",
  "entity.minecraft.villager.dynamicvillage.train_mechanic": "Kỹ sư tàu hỏa",
  "entity.minecraft.villager.dynamicvillage.miner": "Người khai thác quặng",
  "itemGroup.village_life_tab": "Create: Dynamic Villages"
}

**Comment by ben001109** [comment]
You can fork when you complete the language translate file you can pull request

**Comment by a0a7** [comment]
Has been added into the repo! Thanks for the translation! Will add a credit to you
