### ISSUE TITLE
Villager won't use drill to be miner.

### ISSUE THREAD

**Issue by robokillerere** [sudolev/DynamicVillageMod#25]
It just doesn't work.

**Comment by BlizertWarrior** [comment]
If you are using Enchantable Machinery or the more drill heads mod the villagers wont become a miner because the drill isn't really a "vanilla" create drill turn these mods of should fix it. You can also check with Jade from what mod the placed drill is.

**Comment by robokillerere** [comment]
> If you are using Enchantable Machinery or the more drill heads mod the villagers wont become a miner because the drill isn't really a "vanilla" create drill turn these mods of should fix it. You can also check with Jade from what mod the placed drill is.

You're a freaking life saver, thanks.

**Comment by a0a7** [comment]
Yay incompatibilities!
