### ISSUE TITLE
(1.19.2) Hydraulic Engineer sells create:copper_backtank_placeable instead of create:copper_backtank resulting in the trade showing blank(barrier) but still usable after placing it down

### ISSUE THREAD

**Issue by Looxond** [sudolev/DynamicVillageMod#4]
![image](https://github.com/sudolev/DynamicVillageMod/assets/29359853/04dcb241-de3f-469f-87b9-e13a10260407)

**Comment by sudolev** [comment]
Thanks for letting me know. Should be fixed in [v0.2.1](https://modrinth.com/mod/dynamic-village/version/FFIrauQh), which I just published. Not sure how changing the trade will affect your pre-existing villager though.
