### ISSUE TITLE
Broken Zombified Texture (1.19.2)

### ISSUE THREAD

**Issue by FCWYzzr** [sudolev/DynamicVillageMod#5]
# What happened 
when convert to zombies, these variants seem to lost its skin. (replaced by black & purple block)
# How to reproduce
- open game instance
- spawn a villager & give it a moded job (for example, a schema table)
- trade him once for lock his job
- switch difficulty to hard
- spawn a zombie & let it kill this villager
- see what happens.
# probable reason
forget to add a texture or switched texture proxy

**Comment by sudolev** [comment]
Should be fixed in newest version :)
