### ISSUE TITLE
Config on Structure Generation

### ISSUE THREAD

**Issue by HeXiaoYou** [sudolev/DynamicVillageMod#7]
Hi, I was playing this mod in a modpack recently and I really love it. I wonder if there is a config file for this mod to set the rate that the structures generate? I'm not sure whether the modpack changed it or it is just the original rate but villages are full of Miners Camp now. It would be great if this could be altered through config.

**Comment by sudolev** [comment]
There isn't, sorry about that--but you're right, that would be a very good thing to have. However, this mod is pretty much abandoned at this point; it's never really left the testing/early beta stage. I'm sorry to say I'm probably never going to get around to continuing development. Very sorry.

**Comment by Nycto97** [comment]
> There isn't, sorry about that--but you're right, that would be a very good thing to have. However, this mod is pretty much abandoned at this point; it's never really left the testing/early beta stage. I'm sorry to say I'm probably never going to get around to continuing development. Very sorry.

Was about to add this mod, sad to hear that :'( if you ever change your mind and continue development for this mod, could you please reply to this issue so I get notified?
