### ISSUE TITLE
broken texture Zombie Villager (Miner) (all you mod)

### ISSUE THREAD

**Issue by kitovoi111** [sudolev/DynamicVillageMod#8]
![image](https://github.com/sudolev/DynamicVillageMod/assets/147491823/2ed5161b-9725-4d65-9e35-9990a62d3b23)

**Comment by kitovoi111** [comment]
1.19.2 Forge version.

**Comment by kitovoi111** [comment]
![image](https://github.com/sudolev/DynamicVillageMod/assets/147491823/b1d9c7b6-951d-414f-8c87-55687bac2cbd)

All zombie villager (Train Mechanick)

**Comment by DeCoded-Void** [comment]
Duplicate of #5 , same issue. Doesn't look like its going to be fixed.

![image](https://github.com/sudolev/DynamicVillageMod/assets/11778439/c335b19d-fc5e-4838-8055-ac4d0bc7da50)

**Comment by sudolev** [comment]
Should be fixed in newest version :)
